name: Pipeline DevOps IMD

on: [push] # Roda toda vez que você muda o código

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o código
      - uses: actions/checkout@v3

      # 2. Instala Node e Testa (Requisito: Testes)
      - name: Instalar e Testar
        run: |
          npm install
          npm test

      # 3. Login no Docker Hub (Requisito: Imagens)
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 4. Cria a imagem e envia para o Docker Hub
      - name: Build e Push Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Substitua 'seu-usuario' abaixo pelo seu usuário REAL do Docker Hub
          tags: ${{ secrets.DOCKER_USER }}/devops-app:latest

      # 5. Deploy no Kubernetes (Requisito: Deploy Cloud)
      - name: Deploy Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f k8s/deploy.yaml
