name: Pipeline DevOps IMD (Google GKE)

on: [push]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Baixa o c√≥digo
      - uses: actions/checkout@v3

      # 2. Instala Node e Testa
      - name: Instalar e Testar
        run: |
          npm install
          npm test

      # 3. Login no Docker Hub
      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 4. Cria a imagem e envia para o Docker Hub
      - name: Build e Push Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USER }}/devops-app:latest

      # 5. Autenticar no Google Cloud
      - name: Autenticar no Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # 6. Conectar no Cluster GKE
      - name: Configurar GKE Credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          cluster_name: autopilot-cluster-1
          location: us-central1

      # 7. Deploy final no Kubernetes
      - name: Deploy no Kubernetes
        run: |
          kubectl apply -f k8s/deploy.yaml
          kubectl rollout restart deployment/meu-app
